oktana-slack-integration/force-app/main/default/objects/User/fields/SlackID__c.field-meta.xml
<CustomField>
    <fullName>SlackID__c</fullName>
    <label>SlackID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

oktana-slack-integration/force-app/main/default/objects/User/fields/User_Token__c.field-meta.xml
<CustomField>
    <fullName>User_Token__c</fullName>
    <label>User Token</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

oktana-slack-integration/force-app/main/default/classes/UserSelector.cls
public without sharing class UserSelector {
    
    public static List<User> getUsersIdWithToken(){
        List<User> userList = [SELECT Id, User_Token__c FROM User WHERE isActive = true AND SlackID__c != null AND User_Token__c != null ORDER BY Id];
        return userList;
    }
    public static List<User> getUserIdsFromSlackIds(Set<String> slackIds){
        return [SELECT Id, SlackID__c FROM User WHERE SlackID__c IN :slackIds];
    }
}