oktana-slack-integration/force-app/main/default/objects/Debug_Log__c/Debug_Log__c.object-meta.xml
<CustomObject>
    <label>Debug Log</label>
    <nameField>
        <label>Debug Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

oktana-slack-integration/force-app/main/default/objects/Debug_Log__c/fields/isException__c.field-meta.xml
<CustomField>
    <fullName>isException__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This differentiates checkin logs from exception logs. Standard checkin logs should be deleted after 24hours and exception logs should be kept until resolved.</description>
    <label>isException</label>
    <type>Checkbox</type>
</CustomField>

oktana-slack-integration/force-app/main/default/objects/Debug_Log__c/fields/Log_Body__c.field-meta.xml
<CustomField>
    <fullName>Log_Body__c</fullName>
    <label>Log Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

oktana-slack-integration/force-app/main/default/classes/Logger.cls
public class Logger {

    private static List<Object> objects = new List<Object>();
    private static boolean isException = false;

    public static void log(Object register) {
        objects.add(register);
    }
    public static void logException(Object register) {
        objects.add(register);
        isException = true;
    }

    public static void commitWork() {
        String body = JSON.serializePretty(objects);
        Debug_Log__c debuglog = new Debug_Log__c();
        debuglog.Log_Body__c = body;
        debuglog.isException__c = isException;
        insert debuglog;
    }

   
}