oktana-slack-integration/force-app/main/default/objects/Debug_Log__c/Debug_Log__c.object-meta.xml
<CustomObject>
    <label>Debug Log</label>
    <nameField>
        <label>Debug Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

oktana-slack-integration/force-app/main/default/objects/Debug_Log__c/fields/isException__c.field-meta.xml
<CustomField>
    <fullName>isException__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This differentiates checkin logs from exception logs. Standard checkin logs should be deleted after 24hours and exception logs should be kept until resolved.</description>
    <label>isException</label>
    <type>Checkbox</type>
</CustomField>

oktana-slack-integration/force-app/main/default/objects/Debug_Log__c/fields/Log_Body__c.field-meta.xml
<CustomField>
    <fullName>Log_Body__c</fullName>
    <label>Log Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

oktana-slack-integration/force-app/main/default/classes/Tests/LoggerTest.cls
@isTest
public class LoggerTest {

    @isTest
    public static void givenARegisterWhenCallingLoggerDotCommitWorkThenLogIsSuccessfullyInserted() { 
        
        Logger.log('This is a Log');

        Test.startTest();
        Logger.commitWork();
        Test.stopTest();

        Debug_Log__c debuglogExpected = new Debug_Log__c();
        debuglogExpected.Log_Body__c = '[ "This is a Log" ]';
        debuglogExpected.isException__c = false;

        Debug_Log__c debuglogActual = queryOneLog();

        system.assertEquals(debuglogExpected.Log_Body__c, debuglogActual.Log_Body__c);
        system.assertEquals(debuglogExpected.isException__c, debuglogActual.isException__c);
    }

    @isTest
    public static void givenARegisterExceptionWhenCallingLoggerDotCommitWorkThenLogIsSuccessfullyInserted() { 
        
        Logger.logException('This is an Exception Log');

        Test.startTest();
        Logger.commitWork();
        Test.stopTest();

        Debug_Log__c debuglogExpected = new Debug_Log__c();
        debuglogExpected.Log_Body__c = '[ "This is an Exception Log" ]';
        debuglogExpected.isException__c = true;

        Debug_Log__c debuglogActual = queryOneLog();

        system.assertEquals(debuglogExpected.Log_Body__c, debuglogActual.Log_Body__c);
        system.assertEquals(debuglogExpected.isException__c, debuglogActual.isException__c);
    }

    private static Debug_Log__c queryOneLog() {
        return [SELECT Log_Body__c, isException__c FROM Debug_Log__c LIMIT 1][0];
    }
    
}